sudo: required
service: 
    - docker-react

 before_install:
    - docker build -t madhusudanmca:/docker-react-travis Dockerfile.dev .

script: 
    - docker run -r CI=true madhusudanmca:/docker-react-travis npm run test